# Generated by Django 4.0.6 on 2022-07-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telegramId', models.CharField(max_length=100, unique=True)),
                ('lastMessageFromUserAt', models.DateTimeField(null=True)),
                ('LastNotifiedAt', models.DateTimeField(null=True)),
                ('preferedNotificationTime', models.TimeField(null=True)),
            ],
        ),
    ]
